AWSTemplateFormatVersion: '2010-09-09'
Description: 'An EC2 Image Builder pipeline to build DISA STIG compliant RHEL EC2 AMIs.'
Resources:

  ImageBuilderRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder'

  ImageBuilderSSMIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:ListInstanceAssociations
              - ssm:PutComplianceItems
              - ssm:PutConfigurePackageResult
              - ssm:PutInventory
              - ssm:UpdateInstanceAssociationStatus
              - ssm:UpdateInstanceInformation
              - ssmmessages:CreateControlChannel
              - ssmmessages:CreateDataChannel
              - ssmmessages:OpenControlChannel
              - ssmmessages:OpenDataChannel
            Resource: '*'
          - Effect: Allow
            Action:
              - ssm:DescribeDocument
              - ssm:GetDocument
              - ssm:GetManifest
            Resource: 
              - !Sub 'arn:${AWS::Partition}:ssm:*:*:document/AmazonInspector2-InspectorSsmPluginLinux'
              - !Sub 'arn:${AWS::Partition}:ssm:*:*:document/AWS-GatherSoftwareInventory'
      PolicyName: !Sub '${AWS::StackName}-SSMPolicy'
      Roles: 
        - !Ref ImageBuilderRole
  
  ImageBuilderInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref ImageBuilderRole
  ImageBuilderImageRecipe:
    Type: 'AWS::ImageBuilder::ImageRecipe'
    Properties:
      Name: !Sub '${AWS::StackName}-recipe'
      Description: 'RHEL STIG Recipe'
      Version: '1.0.0'
      Components: 
        - ComponentArn: !Sub 'arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:component/amazon-cloudwatch-agent-linux/x.x.x'
        - ComponentArn: !Sub 'arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:component/stig-build-linux-high/x.x.x'
        - ComponentArn: !Sub 'arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:component/scap-compliance-checker-linux/x.x.x'
        - ComponentArn: !Sub 'arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:component/simple-boot-test-linux/x.x.x'
      ParentImage: !Sub 'arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:image/red-hat-enterprise-linux-8-x86/x.x.x'
      BlockDeviceMappings: 
        - DeviceName: '/dev/xvda'
          Ebs:
            DeleteOnTermination: true
            Encrypted: false
            VolumeSize: 8
            VolumeType: 'gp3'
      AdditionalInstanceConfiguration:
        SystemsManagerAgent:
          UninstallAfterBuild: false

  ImageBuilderInfrastructureConfiguration:
    Type: 'AWS::ImageBuilder::InfrastructureConfiguration'
    Properties:
      Name: !Sub '${AWS::StackName}-infra-config'
      InstanceTypes: 
        - 'm6i.large'
      InstanceProfileName: !Ref ImageBuilderInstanceProfile
      Logging: 
        S3Logs: {}
      TerminateInstanceOnFailure: true

  ImageBuilderDistributionConfiguration:
    Type: 'AWS::ImageBuilder::DistributionConfiguration'
    Properties:
      Name: !Sub '${AWS::StackName}-distro'
      Distributions: 
        - 
          Region: !Ref AWS::Region
          AmiDistributionConfiguration: {}

  ImageBuilderImagePipeline:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: !Sub '${AWS::StackName}-pipeline'
      ImageRecipeArn: !Ref ImageBuilderImageRecipe
      InfrastructureConfigurationArn: !Ref ImageBuilderInfrastructureConfiguration
      DistributionConfigurationArn: !Ref ImageBuilderDistributionConfiguration
      ImageTestsConfiguration: 
        ImageTestsEnabled: true
        TimeoutMinutes: 720
      Schedule: 
        ScheduleExpression: 'cron(0 9 ? * mon)'
        PipelineExecutionStartCondition: 'EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE'
      Status: 'ENABLED'